INSERT INTO VARIABLE (ID, NAME, VALUE, DESCRIPTION)
VALUES(1, 'JDBC_URL', 'jdbc:sqlserver://localhost;databaseName=CRM_UAT', null)

INSERT INTO VARIABLE (ID, NAME, VALUE, DESCRIPTION)
VALUES(2, 'JDBC_USERNAME', 'dbclient', null)

INSERT INTO VARIABLE (ID, NAME, VALUE, DESCRIPTION)
VALUES(3, 'JDBC_PASSWORD', 'dbclient123', null)

INSERT INTO VARIABLE (ID, NAME, VALUE, DESCRIPTION)
VALUES(4, 'JDBC_DRIVER', 'com.microsoft.jdbc.sqlserver.SQLServerDriver', null)